param(
    [string]$RenderEnvPath = (Join-Path $PSScriptRoot "..\DongAnhCapital.env")
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
$renderEnv = Resolve-Path -LiteralPath $RenderEnvPath
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Read-EnvExport {
    param([string]$Path)

    $vars = [ordered]@{}
    foreach ($line in [System.IO.File]::ReadLines($Path)) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) {
            continue
        }

        if ($trimmed.StartsWith("export ")) {
            $trimmed = $trimmed.Substring(7).TrimStart()
        }

        $separator = $trimmed.IndexOf("=")
        if ($separator -lt 1) {
            continue
        }

        $name = $trimmed.Substring(0, $separator).Trim()
        $value = $trimmed.Substring($separator + 1)
        $vars[$name] = $value
    }

    return $vars
}

function Write-EnvFile {
    param(
        [string]$Path,
        [string[]]$Lines
    )

    $directory = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory | Out-Null
    }

    [System.IO.File]::WriteAllLines($Path, $Lines, $utf8NoBom)
}

function Add-EnvValue {
    param(
        [System.Collections.Specialized.OrderedDictionary]$Target,
        [string]$Name,
        [string]$Value
    )

    if ($Target.Contains($Name)) {
        $Target[$Name] = $Value
    } else {
        $Target.Add($Name, $Value)
    }
}

$renderVars = Read-EnvExport -Path $renderEnv

$backend = [ordered]@{}
Add-EnvValue $backend "APP_ENV" "local"
Add-EnvValue $backend "API_PORT" "8000"
Add-EnvValue $backend "PORT" "8000"
Add-EnvValue $backend "DATABASE_SSLMODE" "require"
Add-EnvValue $backend "ALLOWED_ORIGINS" "http://localhost:5173,http://127.0.0.1:5173"
Add-EnvValue $backend "FRONTEND_URL" "http://localhost:5173"
Add-EnvValue $backend "GOOGLE_REDIRECT_URI" "http://localhost:5173/auth/google/callback"
Add-EnvValue $backend "COOKIE_SECURE" "false"
Add-EnvValue $backend "COOKIE_DOMAIN" ""
Add-EnvValue $backend "COOKIE_SAMESITE" "lax"

foreach ($name in $renderVars.Keys) {
    if (-not $backend.Contains($name)) {
        Add-EnvValue $backend $name $renderVars[$name]
    }
}

$backendLines = @(
    "# Generated by scripts/setup-local-env.ps1 from DongAnhCapital.env."
    "# Do not commit this file."
) + ($backend.Keys | ForEach-Object { "$_=$($backend[$_])" })

Write-EnvFile `
    -Path (Join-Path $repoRoot "backend\.env") `
    -Lines $backendLines

Write-EnvFile `
    -Path (Join-Path $repoRoot "frontend\.env") `
    -Lines @(
        "# Generated by scripts/setup-local-env.ps1."
        "# Use localhost consistently so browser auth cookies stay same-site."
        "VITE_API_URL=http://localhost:8000/api"
    )

$pipelineLines = @(
    "# Generated by scripts/setup-local-env.ps1 from DongAnhCapital.env."
    "# This pipeline writes to the configured database."
)
if ($renderVars.Contains("DATABASE_URL")) {
    $pipelineLines += "DATABASE_URL=$($renderVars["DATABASE_URL"])"
}
$pipelineLines += "DATABASE_SSLMODE=require"

Write-EnvFile `
    -Path (Join-Path $repoRoot "daily_suggestion_system\.env") `
    -Lines $pipelineLines

Write-Host "Local env files written from Render export:"
Write-Host "  backend/.env"
Write-Host "  frontend/.env"
Write-Host "  daily_suggestion_system/.env"
Write-Host "Secret values were copied locally but not printed."
